### ISSUE TITLE
[Setup] finalize styling of the speaker profiles

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/speakers#10] opened 2022-09-19 10:56 UTC
We already have the structure for what a speaker profile will look like and what parts it will contain. Some styling and formatting is still in progress / to do.

**Comment by osamajandali** [comment] 2022-09-19 13:29
I would like to get more feedback on how it should look to format it in a better way

**Comment by holanita** [comment] 2022-09-20 12:35
I'm not quite sure about the details, I just heard from Asim that you would still be working on the styling.

There is just one thing I'd suggest to change – the headings seem to be too big, bold and green. To me it feels like they distract the attention from the actual content too much. So just on the profile pages, I'd make them smaller than usual.

@jawache do you have specific changes in mind?

**Comment by osamajandali** [comment] 2022-09-25 13:34
Updated the font size for the speakers name

**Comment by jawache** [comment] 2022-10-11 10:12
@osamajandali will setup some time to discuss what's needed here.

**Comment by holanita** [comment] 2022-10-18 10:51
@jawache please let me know if you have an ETA for this

**Comment by jawache** [comment] 2022-10-24 11:05
Copying in content from @holanita in the other ticket:

I'm not quite sure about the details, I just heard from Asim that you would still be working on the styling.

There is just one thing I'd suggest to change – the headings seem to be too big, bold and green. To me it feels like they distract the attention from the actual content too much. So just on the profile pages, I'd make them smaller than usual.

**Comment by jawache** [comment] 2022-10-24 11:07
Duplicate of https://github.com/Green-Software-Foundation/speakers/issues/25 - closing this issue

**Closed by jawache** 2022-10-24 11:07 UTC
Labels: enhancement
